version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "telecast-streams"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-g9w386o5a108"
s3_prefix = "telecast-streams"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
