AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  telecast-streams

  SAM Template for telecast-streams


Globals:
  Function:
    Timeout: 3

Parameters:
  Table:
    Type: String
    Default: Activities
  Region:
    Type: String
    Default: ap-southeast-1


Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
          REGION_NAME: !Ref Region
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ActivitiesTable

  CreateActivityFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.create
      Runtime: python3.8
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
          REGION_NAME: !Ref Region
      Events:
        CreateActivities:
          Type: Api
          Properties:
            Path: /activities
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ActivitiesTable

  ActivitiesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "S"
        -
          AttributeName: "start_time"
          AttributeType: "S"
        -
          AttributeName: "end_time"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
        -
          AttributeName: "start_time"
          AttributeType: "Range"
        -
          AttributeName: "end_time"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: "Activities"
Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  ActivitiesTable:
    Description: "DynamoDB Table"
    Value: !Ref ActivitiesTable
  ActivitiesTableArn:
    Description: "DynamoDB Table ARN"
    Value: !GetAtt ActivitiesTable.Arn
